#!/usr/bin/env python2.7
import socket
import sys

def server_program():
    CHUNK_SIZE = 1024
    counter_dict = {}
    host = "127.0.0.1"
    port = int(sys.argv[1]) 

    while True:
        server_socket = socket.socket()
        server_socket.connect((host, port))  

        data = ''
        while '\r\n\r\n' not in data: 
            data += server_socket.recv(CHUNK_SIZE).decode()



        data_array = data.split(" ") # [GET, /counter, ...]
        counter_dict[data_array[1]] = counter_dict.get(data_array[1], 0) + 1
    
        
        result = "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: " + str(len(str(counter_dict[data_array[1]]))) +"\r\n\r\n"+str(counter_dict[data_array[1]])+"\r\n\r\n"
        result = result.encode()
        server_socket.send(result)  # send result to the client
        
        server_socket.close()




if __name__ == '__main__':
    server_program()